#!/bin/sh
#
# @name Gazebo-Classic roarm_quad
#
# @type Quadrotor
# @class Copter
#
# @maintainer px4
#

# 加载多旋翼默认参数（混控器、PID 基础参数等）
. ${R}etc/init.d/rc.mc_defaults

# 💡 极其重要：告诉 PX4 仿真时去 Gazebo 中加载叫 "roarm_quad" 的模型目录
PX4_SIM_MODEL=roarm_quad
# 💡 设置电池芯数为 6S (6节锂电池串联)
param set-default BAT_N_CELLS 6
